### ISSUE TITLE
Collapse should be able to be created expanded.

### ISSUE THREAD

**Issue by 0x3333** [gwtbootstrap3/gwtbootstrap3-extras#126]
If you use a Collapse with toggle = true when it is loaded it should not animate the expansion.

In the onLoad() method there is a call to:
```java
collapse(getElement(), toggle);
```
We should change to:
```java
if (this.toggle) {
    this.getElement().addClassName("in");
}
```
This way the element will be presented already expanded. In case the user wants it to be animated, he should call ```show()```.

Here is a demo of plain bootstrap behaviour: http://jsfiddle.net/uf61hdv2/1/

**Comment by ArloL** [comment]
Thanks for your report.

Are you talking of this class: https://github.com/gwtbootstrap3/gwtbootstrap3/blob/master/gwtbootstrap3/src/main/java/org/gwtbootstrap3/client/ui/Collapse.java?

I think you might have the wrong repository here. Would you mind opening a new issue at the correct repository: https://github.com/gwtbootstrap3/gwtbootstrap3/issues

Or even better: open a PR with your fix but use `addStyleName("in");` instead of `this.getElement().addClassName("in");`. That'd be great!

**Comment by 0x3333** [comment]
Sorry, my bad, wrong repository.

I'll open a PR.

Thanks.

**Comment by ArloL** [comment]
Great!

**Comment by 0x3333** [comment]
https://github.com/gwtbootstrap3/gwtbootstrap3/pull/296
