### ISSUE TITLE
Sumernote image embed/ drag and drop does not work

### ISSUE THREAD

**Issue by alexdobre** [gwtbootstrap3/gwtbootstrap3-extras#154]
The issue I have is when I want to upload or drag and drop an image file into the sumernote editor. 
You can see the issue in the demo: https://gwtbootstrap3.github.io/gwtbootstrap3-demo/#summernote 
Just try to drag and drop or insert an image via upload into the editor. Nothing happens and the code view also remains unchanged.

Now go and do the same thing on http://summernote.org/#/ and you will see the same process works and the image is embedded as an encoded string.

**Comment by jgodi** [comment]
Yes, the summer note wrapper is a bit behind. If you have time, a PR would be greatly appreciated to get this back up and running!

**Comment by netogildo** [comment]
I managed to fix this by changing the summernote-0.6.2.min.cache.js file on line 1809 (I took the line by http://jsbeautifier.org/ ), which had "f.onImageUpload ? f.onImageUpload(c, h, e) : a.each(c, function(a, b) {" I edited and put just "a.each(c, function(a, b) {" then I replaced the file inside gwtbootstrap3-extras-0.9.1.jar and it worked for me.

**Comment by crevete** [comment]
@alexdobre @netogildo This issue should be fixed now after re-writing the summernote editor for 0.7.0 with plenty of new features. I think the issue was: the wrapper provides an empty implementation for ```onImageUpload``` event. I mean: if you don't add an ```ImageUploadHandler```, the native JS library will also receive an empty callback. Unfortunately, according to the documentation, this will override the default behavior: Insert the base64 encoded image to the editor. That's way the editor does not display the dropped image.
