### ISSUE TITLE
Select:getValue() returns all kinds of values before being added to the dom.

### ISSUE THREAD

**Issue by ahtremblay** [gwtbootstrap3/gwtbootstrap3-extras#321]
```
final Select select = new Select();
select.setTitle("Nothing selected");

Window.alert(select.getValue()); //1 : returns null

Option option = new Option();
option.setValue("1");
option.setText("1");
select.add(option);

Window.alert(select.getValue()); //2 : returns 1
RootPanel.get().add(select);

Window.alert(select.getValue()); //3 : returns "", the empty string


Scheduler.get().scheduleDeferred(new Scheduler.ScheduledCommand() {
            @Override
            public void execute() {

                Window.alert(select.getValue()); //4 : return "", the empty string.
            }
});
```

message box 1 will return null
message box 2 will return 1
message box 3 will return "" 
message box 4 will return ""

even if setValue has never been called or set.

**Comment by ahtremblay** [comment]
Created a wrapper as a workaround. Not pretty but it gets the job done.

`public class CorrectedSelect extends Select {

    private String v;

    public CorrectedSelect() {
        addAttachHandler(new AttachEvent.Handler() {
            @Override
            public void onAttachOrDetach(AttachEvent attachEvent) {
                if (attachEvent.isAttached()){
                    setValue(v);
                }
            }
        });
    }

    @Override
    public String getValue() {
        if (super.getValue()==null || super.getValue().isEmpty())
            return null;

        if (v!=null)
            return super.getValue();

        if (!isAttached())
            return null;

        return super.getValue();
    }

    @Override
    public void setValue(String value, boolean fireEvents) {
        v=value;
        super.setValue(value, fireEvents);
    }
}`

**Comment by crevete** [comment]
It looks strange, but it is normal. Please note that before the select being attached to DOM, the select widget is just like a simple HTML ```<select>```.
- message box 1: No option, return null (set by Java code, natively it should be empty string)
- message box 2: Only one option, return the option's value, because the ```option.selected=true```
- message box 3 and 4: already attached to DOM, we just call ```.selectpicker('val')``` method to get value, and it returns empty string. Here, we cannot return ```null``` when bootstrap select returns empty string, because an option may have an empty value.

If you want to change the return value, you can override it like you did.
