### ISSUE TITLE
com.google.gwt.user.client.ui.AttachDetachException: Exception caught: Exception caught: (TypeError) : $wnd.jQuery(...).datepicker is not a function

### ISSUE THREAD

**Issue by valeriofinazzo** [gwtbootstrap3/gwtbootstrap3-extras#345]
Hi,
using date picker on gwt 2.8.2 on superdev mode i receive this error
com.google.gwt.user.client.ui.AttachDetachException: Exception caught: Exception caught: (TypeError) : $wnd.jQuery(...).datepicker is not a function

this is my configuration

<module rename-to="frontEnd">
	<inherits name="com.google.gwt.user.User" />
	<inherits name="org.fusesource.restygwt.RestyGWT" />
	<inherits name="gwt.material.design.GwtMaterialDesignBasic" />
	<inherits name="org.gwtbootstrap3.extras.datepicker.DatePicker"/>

**Comment by sjardine** [comment]
This is most likely due to the fact that gwtbootstrap3 has been injected more than once. Please check the group and GitHub issues for more info. It has been covered extensively.

On Jul 28, 2018, 2:21 PM, at 2:21 PM, valeriofinazzo <notifications@github.com> wrote:
>Hi,
>using date picker on gwt 2.8.2 on superdev mode i receive this error
>com.google.gwt.user.client.ui.AttachDetachException: Exception caught:
>Exception caught: (TypeError) : $wnd.jQuery(...).datepicker is not a
>function
>
>this is my configuration
>
><module rename-to="frontEnd">
>	<inherits name="com.google.gwt.user.User" />
>	<inherits name="org.fusesource.restygwt.RestyGWT" />
>	<inherits name="gwt.material.design.GwtMaterialDesignBasic" />
>	<inherits name="org.gwtbootstrap3.extras.datepicker.DatePicker"/>
>
>--
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/gwtbootstrap3/gwtbootstrap3-extras/issues/345


IMPORTANT: This email does not constitute a contract or an offer or acceptance of an offer to enter into a contract.  Further, this email may not be used to modify, supplement, novate, or waive any rights with respect to an existing contract or other binding commercial terms. MJN Services, Inc. conducts business under our service terms and conditions found at www.mjnservices.com unless otherwise agreed to in writing by an officer of MJN Services, Inc.

**Comment by valeriofinazzo** [comment]
Hi Steven, 
many thanks for your reply
i resolved doing this:

in .gwt.xml 
	<inherits name="org.gwtbootstrap3.extras.datepicker.DatePicker"/>

in onModuleLoad() i used

if (!isJQueryLoaded()) {
			ScriptInjector.fromUrl("https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js")
	        .setWindow(ScriptInjector.TOP_WINDOW).setRemoveTag(true).inject();
		}

private native boolean isJQueryLoaded() /*-{
	    return (typeof $wnd['jQuery'] !== 'undefined');
	}-*/
